### ISSUE TITLE
Cannot access com.google.protobuf.GeneratedMessageV3 Java error

### ISSUE THREAD

**Issue by DiegoJohnsonL** [husnjak/IGDB-API-JVM#11]
Hello, first of all thanks for the all the work to build this library. I wanted to use it on java but came across an error that happens when trying to access the getter functions in the proto.Game class. 

Error Image: 
![image](https://user-images.githubusercontent.com/54253758/122624573-5ec2d300-d066-11eb-85c2-f3de24961bc8.png)

**Comment by sitatec** [comment]
I have the same error. Have you fixed it?

**Comment by sitatec** [comment]
Adding Google Protobuf as a dependency in the app module's build.gradle works for me:
`implementation 'com.google.protobuf:protobuf-java:3.15.3'`

**Comment by DiegoJohnsonL** [comment]
> Adding Google Protobuf as a dependency in the app module's build.gradle works for me:
> `implementation 'com.google.protobuf:protobuf-java:3.15.3'`

Thank you very much!
