### ISSUE TITLE
Wrapper incompatible with Android

### ISSUE THREAD

**Issue by husnjak** [husnjak/IGDB-API-JVM#2]
There is an issue when adding the wrapper to an Android project as an dependency where we are met with the error:

```
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - org.eclipse.sisu.inject-0.0.0.M5.jar (org.eclipse.sisu:org.eclipse.sisu.inject:0.0.0.M5)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

Debugging the issue leads to Googles Protocol buffers which are used to build the generated classes for the API. 

Solutions
 - find alternative protobuf library that does not use the org.eclipse.sisu:org.eclipse.sisu.inject:0.0.0.M5.jar
- Create a new library without generated classes.

**Comment by abalta** [comment]
I need this wrapper for my android project.

**Comment by husnjak** [comment]
Should work now with version 0.7

**Comment by abalta** [comment]
Thank you, how can I log network request.
