### ISSUE TITLE
RequestException

### ISSUE THREAD

**Issue by gitadam0** [husnjak/IGDB-API-JVM#22]
hello brother I think I follow all the steps but I  just cant get it to work

 I enter the CLIENT_ID and ACCESS_TOKEN but ill always catch RequestException 
and i get this the run console :  Skipped 34 frames!  The application may be doing too much work on its main thread.

CODE  :
"""
IGDBWrapper wrapper = IGDBWrapper.INSTANCE;
wrapper.setCredentials("CLIENT_ID", "ACCESS_TOKEN")
APICalypse apicalypse = new APICalypse().fields("*").sort("release_dates.date", Sort.DESCENDING);
try{
  List<Game> games = ProtoRequestKt.games(wrapper, apicalypse);
} catch(RequestException e) {
  // Do something or error
}
"""

**Comment by gpcalmeida** [comment]
Are you running this code on main thread? This can be the problem.
You can try to attach this request to a different dispatcher using Coroutines

**Comment by gitadam0** [comment]
> Are you running this code on main thread? This can be the problem. You can try to attach this request to a different dispatcher using Coroutines

yes bro that was the problem, thanks its fixed now
