### ISSUE TITLE
Protobuff versions mismatch

### ISSUE THREAD

**Issue by iserb** [husnjak/IGDB-API-JVM#9]
Hi there. Looks like last version has protobuf version mismatch. If you try to create simple class it will not compile showing compilation error 
`java: cannot access com.google.protobuf.CodedInputStream
  class file for com.google.protobuf.CodedInputStream not found`

In your `build.gradle.kts` file you are using 
`implementation("com.google.protobuf:protobuf-java:3.11.0")` 
but  
`artifact = "com.google.protobuf:protoc:3.13.0"` 
and this version mismatch is causing compilation error
However, if you explicitly configure maven or graddle to use protobuf-java 3.13.0 the error goes away.

Hopefully this will help to fix this error

**Comment by husnjak** [comment]
Fixing this in the next update!
